ReportSystem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from report import views as report_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('reports/', include('report.urls')),
]

accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    # Login/Logout
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),

    # Redirect after login
    path('dashboard/', views.dashboard, name='dashboard'),

    # Dashboards
    path('mdi_dashboard/', views.mdi_dashboard, name='mdi_dashboard'),
    path('client_dashboard/', views.client_dashboard, name='client_dashboard'),

    # Access Denied
    path('access_denied/', views.access_denied, name='access_denied'),

    # Password Reset
    path('password-reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),

    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

]

report/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'report'

urlpatterns = [
    # Report
    path('create_report/', views.create_report, name='create_report'),
    path('display_report/', views.display_report, name='display_report'),
    path('report/<int:report_id>/', views.view_report, name='view_report'),
    path('update/<int:report_id>/', views.update_report, name='update_report'),
    path('report/<int:report_id>/export/', views.export_report_pdf, name='export_report_pdf'),
    path('report/<int:report_id>/export-word/', views.export_report_word, name='export_report_word'),
    path('report/<int:report_id>/export-csv/', views.export_report_csv, name='export_report_csv'),
    path('report/import/', views.import_report_csv, name='import_report'),

    # Asset
    path('create_asset/', views.create_asset, name='create_asset'),
    path('assets/', views.display_assets, name='display_assets'),
    path('assets/<int:asset_id>/', views.view_asset, name='view_asset'),
    path('assets/update/<int:asset_id>/', views.update_asset, name='update_asset'),

    # Problem Type
    path('create_problem_type/', views.create_problem_type, name='create_problem_type'),
    path('problem_type/', views.display_problem_type, name='display_problem_type'),
    path('problem_type/update/<int:problem_type_id>/', views.update_problem_type, name='update_problem_type'),


    path('assets1/update-parent/', views.update_asset_parent, name='update_asset_parent'),

]

accounts/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from .decorators import allowed_roles_or_permissions

"""
@allowed_roles_or_permissions(roles=['MDI Team'])
@allowed_roles_or_permissions(permissions=['reports.add_report'])
@allowed_roles_or_permissions(roles=['MDI Team'], permissions=['reports.add_report'])

"""

@login_required
def dashboard(request):
    user = request.user
    if user.groups.filter(name="MDI Team").exists():
        return redirect('mdi_dashboard')
    elif user.groups.filter(name="Client").exists():
        return redirect('client_dashboard')
    else:
        return redirect('access_denied')

@login_required
@allowed_roles_or_permissions(roles=['MDI Team'])
def mdi_dashboard(request):
    return render(request, 'mdi_dashboard.html')

@login_required
@allowed_roles_or_permissions(roles=['Client'])
def client_dashboard(request):
    return render(request, 'client_dashboard.html')

def access_denied(request):
    return render(request, 'access_denied.html')

accounts/templates/access_denied.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Access Denied</title>
    <link rel="stylesheet" href="{% static 'css/access_denied.css' %}">
</head>
<body>
    <div class="container">
        <h1>Access Denied</h1>
        <p>Oops! You don’t have permission to view this page.</p>
        <a href="{% url 'login' %}">Go to Login</a>
    </div>
</body>
</html>

accounts/templates/client_dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Client Dashboard</title>
    <link rel="stylesheet" href="{% static 'css/mdi_dashboard.css' %}">
</head>
<body>
    <header>
        Client Dashboard
        <form method="post" action="{% url 'logout' %}" style="display:inline; float:right;">
            {% csrf_token %}
            <button type="submit" class="logout-btn">Logout</button>
        </form>
    </header>
        <div class="container">
        <h1>Welcome, {{ request.user.username }}</h1>

        <div class="dashboard-card">
            <p><a href="{% url 'report:display_report' %}"> Reports </a></p>
        </div>
    </div>
</body>
</html>

accounts/templates/mdi_dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>MDI Dashboard</title>
    <link rel="stylesheet" href="{% static 'css/mdi_dashboard.css' %}">
</head>
<body>
    <header>
        MDI Dashboard
        <form method="post" action="{% url 'logout' %}" style="display:inline; float:right;">
            {% csrf_token %}
            <button type="submit" class="logout-btn">Logout</button>
        </form>
    </header>
        <div class="container">
        <h1>Welcome, {{ request.user.username }}</h1>
        <div class="dashboard-card">
            <p><a href="{% url 'report:display_report' %}"> Reports </a></p>
            <p><a href="{% url 'report:display_assets' %}"> Assets </a></p>
            <p><a href="{% url 'report:display_problem_type' %}"> Problem Types </a></p>
        </div>
    </div>
</body>
</html>